### ISSUE TITLE
怎么设置右侧toc不在封面显示QAQ

### ISSUE THREAD

**Issue by Heachy** [xxxxue/Docsify-Build-Sidebar#11]
![image](https://github.com/xxxxue/Docsify-Build-Sidebar/assets/90972647/1399ed09-9239-4372-8abb-9602945e9fc3)

> 如果封面和首页在同一页的话，toc就会固定在右上角了

**Comment by xxxxue** [comment]
你可以尝试 创建一个 `get-start.md` 文件( 名字随意,这里用 get-start 举例 ), 把 `README.md` 的内容 剪切进去,
然后把 `README.md` 的内容和 `_sidebar.md` 保持一致,
`_coverpage.md` 中 修改 `[开始阅读](/get-start)`

**Comment by Heachy** [comment]
> 你可以尝试 创建一个 `get-start.md` 文件( 名字随意,这里用 get-start 举例 ), 把 `README.md` 的内容 剪切进去, 然后把 `README.md` 的内容和 `_sidebar.md` 保持一致, `_coverpage.md` 中 修改 `[开始阅读](/get-start)`

有用，谢谢！

**Comment by Heachy** [comment]
> 你可以尝试 创建一个 `get-start.md` 文件( 名字随意,这里用 get-start 举例 ), 把 `README.md` 的内容 剪切进去, 然后把 `README.md` 的内容和 `_sidebar.md` 保持一致, `_coverpage.md` 中 修改 `[开始阅读](/get-start)`

但是貌似只是把READEME的二级标题给去掉了，因为_sidebar.md里没有二级标题，如果README有二,三级标题还是会有toc，这个操作貌似只是更改了开始阅读的跳转链接
![image](https://github.com/xxxxue/Docsify-Build-Sidebar/assets/90972647/bb27b088-63f9-48a9-b76b-1117ba246f60)

**Comment by Heachy** [comment]
![image](https://github.com/xxxxue/Docsify-Build-Sidebar/assets/90972647/3448681e-bf98-4b53-a073-40a8c630d07e)
就是这个侧边栏绿色的小条条貌似不是根据浏览到哪个部分就固定在哪个部分，是我这边的问题吗QAQ

**Comment by xxxxue** [comment]
> 就是这个侧边栏绿色的小条条貌似不是根据浏览到哪个部分就固定在哪个部分，是我这边的问题吗QAQ

这个好像是因为你 `没有按顺序写标题`
例如
```
# 嘿嘿嘿
#### 啊哈哈
```
改成 
```
# 嘿嘿嘿
## 啊哈哈
```

**Comment by xxxxue** [comment]
> > 你可以尝试 创建一个 `get-start.md` 文件( 名字随意,这里用 get-start 举例 ), 把 `README.md` 的内容 剪切进去, 然后把 `README.md` 的内容和 `_sidebar.md` 保持一致, `_coverpage.md` 中 修改 `[开始阅读](/get-start)`
> 
> 但是貌似只是把READEME的二级标题给去掉了，因为_sidebar.md里没有二级标题，如果README有二,三级标题还是会有toc，这个操作貌似只是更改了开始阅读的跳转链接 

这个看起来是正常的.  因为 默认的 homepage 就是 README.md .  
toc 配置中指定从 h2 开始生成的. 
第一屏只是一个大图, 实际内容已经在下面渲染了.

这个有个临时的解决方案就是 升级到最新的 docsify-plugin-toc
```html

<link href="
https://cdn.jsdelivr.net/npm/docsify-plugin-toc@1.3.2/dist/light.min.css
" rel="stylesheet">

<script src="
https://cdn.jsdelivr.net/npm/docsify-plugin-toc@1.3.2/dist/docsify-plugin-toc.min.js
"></script>
```

新版有个  `ignoreHeader` 属性, 可以配置忽略的标题. 
你只要把 README.md 中的 `所有标题` 都加进去就可以了. 或者设置一个标志, 用正则统一忽略
```js
toc: {
    tocMaxLevel: 5,
    target: 'h2, h3, h4, h5, h6',
    ignoreHeader:  ['react', 'vue']
  },
```
这样设置后下面的标题就不会生成了. (只要内容相同就会忽略. 不管是几级的标题)
```markdown
## react
### vue
```

源码中是用 match 来判断的. 
```js
if (ignoreHeaders.length > 0) {
     needSkip = ignoreHeaders.some(str => innerText.match(str))
}
```


还有个终极的解决方案. 就是 自己修改他的源码. 
现在是只有内容相同就忽略,  你可以给他加一个 `url 地址` 匹配到了, 就跳过生成 toc.

修改后的源码可以直接放在 index.html 的 script 中执行. 
或者放在自己的 github 中, jsdelivr 支持 [使用 github 地址来加载文件](https://www.jsdelivr.com/?docs=gh).  把 index.html 的 toc 文件改为 你修改后的文件

**Comment by Heachy** [comment]
> > 就是这个侧边栏绿色的小条条貌似不是根据浏览到哪个部分就固定在哪个部分，是我这边的问题吗QAQ
> 
> 这个好像是因为你 `没有按顺序写标题` 例如
> 
> ```
> # 嘿嘿嘿
> #### 啊哈哈
> ```
> 
> 改成
> 
> ```
> # 嘿嘿嘿
> ## 啊哈哈
> ```

谢谢，可以了，发现是我`tocMaxLevel `和`target`设置没有对应上

**Comment by Heachy** [comment]
### [原文链接](https://github.com/xxxxue/Docsify-Build-Sidebar/issues/11#issuecomment-1913621615)
### 相关图片
![image](https://github.com/xxxxue/Docsify-Build-Sidebar/assets/90972647/c48c6c1c-5b10-4e28-b49b-ab73e81fc93b)
![image](https://github.com/xxxxue/Docsify-Build-Sidebar/assets/90972647/9987266c-caa1-4cf7-8b00-a160e6224b70)
![image](https://github.com/xxxxue/Docsify-Build-Sidebar/assets/90972647/750822fb-5438-4778-bb20-8cb512bbabdf)
这边我是都有加进去的，js文件也改成你提供的链接了，可貌似还是不行
