### ISSUE TITLE
隐藏指定的文件夹和文件

### ISSUE THREAD

**Issue by Adubyp** [xxxxue/Docsify-Build-Sidebar#3]
请问是否可以在配置文件中增加一个或者几个配置项目,以便忽略指定的文件和文件夹?比如忽略 **_media** / **assets** / **.nojekyll** 等...

**Comment by xxxxue** [comment]
好的，最近搞一搞。

目前你可以直接在源码中加入你想要忽略的文件或文件夹，然后自己编译，先用着。

**Comment by Adubyp** [comment]
好的，谢谢您
