### ISSUE TITLE
README.md覆盖

### ISSUE THREAD

**Issue by taozhu1** [xxxxue/Docsify-Build-Sidebar#4]
能否将是否生成 README.md 文件设置为可配置的？

习惯性在README.md里写一些东西，但每次都会被覆盖掉。

**Comment by xxxxue** [comment]
我先评估一下，
如果可行，下个版本增加一个 对应的开关配置。
可能会一两天。

同时也欢迎 PR

**Comment by xxxxue** [comment]
新版本发布了. 你可以测试一下

**Comment by taozhu1** [comment]
好用，已经起飞
