### ISSUE TITLE
哥自动生成导航栏目录兼用一下中文目录吧，玩电脑目录命名规则一塌糊涂，目录不写中文过几天就忘，拼音也忘救救孩子吧o(╥﹏╥)o

### ISSUE THREAD

**Issue by qingshanglei** [xxxxue/Docsify-Build-Sidebar#7]

**Comment by qingshanglei** [comment]
[](![image](https://github.com/xxxxue/Docsify-Build-Sidebar/assets/101866574/4f89caa6-7995-4cb0-8f88-544b1ec16f9d))

**Comment by qingshanglei** [comment]
![image](https://github.com/xxxxue/Docsify-Build-Sidebar/assets/101866574/9c0221fd-fba4-4aa5-9789-564867cfa7e1)

**Comment by xxxxue** [comment]
中文好像没有问题...

![image](https://github.com/xxxxue/Docsify-Build-Sidebar/assets/32764266/071f33b3-723d-4ba5-9eda-c5eab4680de6)

子目录中文也没有问题(我一直在用中文名称)
![image](https://github.com/xxxxue/Docsify-Build-Sidebar/assets/32764266/552f9721-9916-4c6b-8860-59d0981d7524)

**Comment by qingshanglei** [comment]
刚看到抱歉，我把中文暂时改为英文，启动应用后，用VS Code批量修改名称，改回中文搞好了，可能是我操作失误了，抱歉啊

&nbsp;


《魔鬼的眼泪》
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月17日(星期六) 下午2:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xxxxue/Docsify-Build-Sidebar] 哥自动生成导航栏目录兼用一下中文目录吧，玩电脑目录命名规则一塌糊涂，目录不写中文过几天就忘，拼音也忘救救孩子吧o(╥﹏╥)o (Issue #7)





 
中文好像没有问题...
 

 
子目录中文也没有问题(我一直在用中文名称)
